name: Deployment

on:
  push:
    branches:
      - master

jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Setup .NET 8
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '8.0.x'
        include-prerelease: true
        
    - name: publish
      run: |
        cd testDeploy
        dotnet publish -c release
      
    - name: Change base-tag in index.html from / to the necessary
      run: sed -i 's/<base href="\/" \/>/<base href="\/TypeInfo\/" \/>/g' ./testDeploy/bin/release/net6.0/publish/wwwroot/index.html
      
    - name: Add .nojekyll file
      run: touch ./testDeploy/bin/release/net6.0/publish/wwwroot/.nojekyll
      
    - uses: JamesIves/github-pages-deploy-action@4.1.4
      name: gh-pages publish
      with:
        branch: gh-pages
        folder: ./testDeploy/bin/release/net6.0/publish/wwwroot
